server: 
    port: 8881 
    context-path: /moon 
spring: 
## none, update, create, create-drop
## none This is the default for MySQL, no change to the database structure
## update Hibernate changes the database according to the given Entity structures
## create Creates the database every time, but don\u2019t drop it when close.
## create-drop Creates the database then drops it when the SessionFactory closes.
    jpa: 
        hibernate: 
            ddl-auto: none
        show-sql: true
        properties: 
            format_sql: true
    datasource: 
        url: jdbc:mysql://localhost:3306/moonschema
        username: root
        password: zy19880330
    activemq: 
        user: admin 
        password: admin 
        broker-url: tcp://127.0.0.1:61616 
        pool: 
            enabled: true
            configuration: 
                max-connections: 10
queueName: publish.queue 
topicName: publish.topic 
security: 
    basic: 
        enabled: false